# Generated by Django 5.1.4 on 2024-12-22 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account_balance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('ref_id', models.CharField(max_length=20)),
                ('misc_fees', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('commissions_and_fees', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('action', models.CharField(max_length=10)),
                ('shares', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
