# Generated by Django 5.1.4 on 2024-12-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_app', '0002_trade_pnl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='pnl',
        ),
        migrations.AddField(
            model_name='trade',
            name='symbol',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
