# Generated by Django 5.1.4 on 2024-12-22 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_app', '0003_remove_trade_pnl_trade_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailybalance',
            name='prev_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
