# Generated by Django 5.1.4 on 2025-01-01 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_app', '0004_dailybalance_prev_balance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trade',
            new_name='Order',
        ),
    ]
